import { scaleLinear, scaleSequential } from 'd3-scale'
import { interpolateWarm } from 'd3-scale-chromatic'
import { getRgbaColor, defaultConfigValues } from '@cosmos.gl/graph'
function getRandom (min: number, max: number): number { return Math.random() * (max - min) + min }
function getPositionOnCircle (radius: number, angle: number, center: number): [number, number] { return [center + radius * Math.cos(angle), center + radius * Math.sin(angle)] }
export type MeshData = { pointPositions: Float32Array; pointColors: Float32Array; pointSizes: Float32Array; links: Float32Array; linkColors: Float32Array; linkWidths: Float32Array; pointClusters: number[]; clusterPositions: number[]; clusterStrength: Float32Array }
export function generateMeshData (n: number, m: number, nClusters: number, wholeness: number, radialness = [10, 1000]): MeshData {
  const pointColorScale = scaleSequential(interpolateWarm); pointColorScale.domain([0, nClusters]); const radius = scaleLinear(radialness); radius.domain([0, nClusters]); const count = n * m
  const pointPositions = new Float32Array(count * 2); const links: number[] = []; const pointClusters = new Array(count); const clusterPositions = new Array(nClusters * 2); const clusterStrength = new Float32Array(count); const pointColors = new Float32Array(count * 4); const pointSizes = new Float32Array(count); const spaceSize = defaultConfigValues.spaceSize
  for (let clusterIndex = 0; clusterIndex < nClusters; clusterIndex++) { const [x, y] = getPositionOnCircle(radius(clusterIndex), 15 * Math.PI * (clusterIndex / nClusters), spaceSize / 2); clusterPositions[clusterIndex * 2] = x; clusterPositions[clusterIndex * 2 + 1] = y }
  for (let pointIndex = 0; pointIndex < count; pointIndex++) { const x = spaceSize * getRandom(0.495, 0.505); const y = spaceSize * getRandom(0.495, 0.505); pointPositions[pointIndex * 2] = x; pointPositions[pointIndex * 2 + 1] = y; pointClusters[pointIndex] = pointIndex % nClusters; clusterStrength[pointIndex] = (nClusters - (pointIndex % nClusters)) / nClusters; const rgba = getRgbaColor(pointColorScale(pointIndex % nClusters)); pointColors.set(rgba, pointIndex * 4); pointSizes[pointIndex] = getRandom(1, 5); const next = pointIndex + 1; const bottom = pointIndex + n; const line = Math.floor(pointIndex / n); if (line === Math.floor(next / n) && Math.random() < wholeness) links.push(pointIndex, next); if (Math.floor(bottom / n) < m && Math.random() < wholeness) links.push(pointIndex, bottom) }
  const linkColors = new Float32Array(links.length / 2 * 4); const linkWidths = new Float32Array(links.length / 2); for (let i = 0; i < links.length / 2; i++) { const rgba = getRgbaColor(pointColorScale((links[i * 2] as number) % nClusters)); linkColors.set([rgba[0], rgba[1], rgba[2], 0.9], i * 4); linkWidths[i] = getRandom(0.4, 0.8) }
  return { pointPositions, pointColors, pointSizes, links: new Float32Array(links), linkColors, linkWidths, pointClusters, clusterStrength, clusterPositions }
}
